#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
pushd $DOTFILES
export DOTFILES=$HOME/.dotfiles
export STOW_FOLDERS="bash, nvim, qutebrowser, tmux, zsh, sway, swaylock, mako, waybar, wofi"
export PATH=$DOTFILES/scripts:$PATH
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd
